#String Methods - string methods are built-in functions that operate on string objects.
#They are called using the dot (.) notation, and most of them return a new string without modifying the origina
name = input ("Enter your name: ")
print(len(name))
#print(name.isalpha())
#print(name.isdecimal())
#print(name.find(" "))
#print(name.rfind("d"))
#print(name.capitalize())
#print(name.upper())
#print(name.lower())
#print (name.replace("-"," "))
#print(name.title())
#print(name.startswith("Hello"))
#print(name.endswith("world"))
#print(name.split())
#print(name.count("a"))
#print(name.strip())
#print(name.isalnum())
