#List-multiple values stored in one variable
#a list is a built-in data type used to store an ordered, mutable collection of items,duplicates are allowed.
students=["Sam","Balu","Deepika","Atchaya"]
mark=[56,85,90,93]
#print(len(students))
#print(dir(students))
#print(help(students))
#print("Sam" in students)
#print(students)
#print(students[0])
#print(students[0:4])
#print(students[::-1])
#students.append("Kayal")
#print(students.count("sam"))
#print(students)
#students.reverse()
#print(students.index("Balu"))
#students.sort()
#students.insert(0,"Sana")
#students.remove("Balu")
#students.pop()
#students.clear()
#print(students)
#print(mark)
#print(mark+students) 
#print(mark * 3)
