name = input ("Enter your name: ")
print(len(name))
print(name.isalpha())
print(name.isdecimal())
print(name.find(" "))
print(name.rfind("d"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print (name.replace("-"," "))